### ISSUE TITLE
Info wss closed 是什么错误

### ISSUE THREAD

**Issue by TihPct** [Kloping/qqpd-bot-java#3]

**Comment by Kloping** [comment]
日志

**Comment by TihPct** [comment]
> 是不是过一段时间就closed

是的,而且在调用run方法后,会出现如下报错信息
`[github.kloping.ST][Error] [03/10-20:17:00:475]=>wss error
java.lang.ClassCastException: class com.alibaba.fastjson2.JSONObject cannot be cast to class com.alibaba.fastjson.JSONObject (com.alibaba.fastjson2.JSONObject and com.alibaba.fastjson.JSONObject are in unnamed module of loader 'app')
	at io.github.kloping.qqbot.WssWorker$1.onMessage(WssWorker.java:81)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:462)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:389)
	at io.github.kloping.qqbot.WssWorker.run(WssWorker.java:142)
	at io.github.kloping.qqbot.Starter.lambda$wssWork$0(Starter.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by TihPct** [comment]
> 是不是过一段时间就closed

`[github.kloping.ST][Debug] [03/10-20:18:00:452]=>wss closed 该日志具体内容`

**Comment by Kloping** [comment]
> > 是不是过一段时间就closed
> 
> `[github.kloping.ST][Debug] [03/10-20:18:00:452]=>wss closed 该日志具体内容`

可以设置 自动重连
starter.getWssWorker().setReconnect(true);

https://github.com/Kloping/qqpd-bot-java/blob/master/src/main/java/io/github/kloping/qqbot/WssWorker.java#L225

**Comment by TihPct** [comment]
> > > 是不是过一段时间就closed
> > 
> > 
> > `[github.kloping.ST][Debug] [03/10-20:18:00:452]=>wss closed 该日志具体内容`
> 
> 可以设置 自动重连 starter.getWssWorker().setReconnect(true);
> 
> https://github.com/Kloping/qqpd-bot-java/blob/master/src/main/java/io/github/kloping/qqbot/WssWorker.java#L225

OK,我已经将此段代码写入,正在验证是否还会出现该问题

**Comment by TihPct** [comment]
> > > 是不是过一段时间就closed
> > 
> > 
> > `[github.kloping.ST][Debug] [03/10-20:18:00:452]=>wss closed 该日志具体内容`
> 
> 可以设置 自动重连 starter.getWssWorker().setReconnect(true);
> 
> https://github.com/Kloping/qqpd-bot-java/blob/master/src/main/java/io/github/kloping/qqbot/WssWorker.java#L225
![image](https://user-images.githubusercontent.com/51705716/224317351-17e4f357-dbb8-4ce5-bae1-f06b632f520d.png)
我抓取了一下重连部分的代码,发现参数的判断好像写的有问题,将Reconnect设置为true时,仍然不会执行`     
if (isReconnect && !connected) {
           reConnect();
}`这部分代码

**Comment by Kloping** [comment]
![~O74Q@{2TVPOFL)K82%@ERX](https://user-images.githubusercontent.com/87743020/224318737-622cd32f-ef57-4daf-96bd-24483f4df429.png)

**Comment by Kloping** [comment]
![image](https://user-images.githubusercontent.com/87743020/224318884-f41c2506-a20d-47b3-87c5-4c746df61499.png)

**Comment by TihPct** [comment]
> > ![~O74Q@{2TVPOFL)K82%@ERX](https://user-images.githubusercontent.com/87743020/224318737-622cd32f-ef57-4daf-96bd-24483f4df429.png)
> 
> ![QQ图片20230310203318](https://user-images.githubusercontent.com/51705716/224318834-62fb8475-97a0-4739-a074-bd1d467fb3ed.png)
> 
> 写法跟您提供的用例是一样的

![image](https://user-images.githubusercontent.com/51705716/224319263-cb9a3b7b-d091-4b21-8370-cdd2bc5b1699.png)

**Comment by Kloping** [comment]
在wss closed 之前没有 [服务端通知客户端重新连接](https://bot.q.qq.com/wiki/develop/api/gateway/opcode.html) 的信息

**Comment by Kloping** [comment]
类似于 
![image](https://user-images.githubusercontent.com/87743020/224319970-c07e3d31-dcaa-44f6-af76-68cedd190954.png)

**Comment by TihPct** [comment]
> 类似于 ![image](https://user-images.githubusercontent.com/87743020/224319970-c07e3d31-dcaa-44f6-af76-68cedd190954.png)

![image](https://user-images.githubusercontent.com/51705716/224320252-f56ab166-ef2a-4983-b65e-c6f57b438d04.png)
貌似并没有收到类似的日志信息

**Comment by Kloping** [comment]
从启动到closed 多久时间

**Comment by Kloping** [comment]
> 从启动到closed 多久时间

之前测试都是半个小时colsed一次

**Comment by TihPct** [comment]
> > 从启动到closed 多久时间
> 
> 之前测试都是半个小时colsed一次

[github.kloping.ST][Info]  [03/10-20:51:48:090]=>start sptool success
[github.kloping.ST][Debug] [03/10-20:53:13:396]=>wss closed
大约在两分钟左右

**Comment by Kloping** [comment]
![image](https://user-images.githubusercontent.com/87743020/224322057-358341ed-adc2-42dd-8ebc-1fbfbb19c0a5.png)
正常尝试解决 如果你也感兴趣 也可以pr

**Comment by TihPct** [comment]
> ![image](https://user-images.githubusercontent.com/87743020/224322057-358341ed-adc2-42dd-8ebc-1fbfbb19c0a5.png) 正常尝试解决 如果你也感兴趣 也可以pr

好的

**Comment by TihPct** [comment]
好像是FastJson版本冲突问题,我Clone了代码到本地运行,就不会发生每两分钟就自动进行wss closed操作了

**Comment by TihPct** [comment]
并且也不会出现JSON解析异常的情况https://github.com/Kloping/qqpd-bot-java/issues/3#issuecomment-1463725360

**Comment by TihPct** [comment]
问题已经确认,FastJson2.0.20版本对于泛型处理存在一些问题,导致泛型无法被解析,进而引发`Pack<JSONObject> pack = JSON.parseObject(s).toJavaObject(Pack.class);`无法被转换,`pack.getOp()`操作也就无法正常进行

**Comment by Kloping** [comment]
我该怎么复现的你的问题 来确定是否修复了呢

**Comment by TihPct** [comment]
> 我该怎么复现的你的问题 来确定是否修复了呢

只需要将FastJson版本更换为2.0.20即可复现

**Comment by Kloping** [comment]
试试预发版本1.4.3-M2 是否解决问题

**Comment by TihPct** [comment]
> 试试预发版本1.4.3-M2 是否解决问题

好的

**Comment by TihPct** [comment]
> > 试试预发版本1.4.3-M2 是否解决问题
> 
> 好的

更换至1.4.3-M2版本后,JSON解析正常

**Comment by TihPct** [comment]
> > > 试试预发版本1.4.3-M2 是否解决问题
> > 
> > 
> > 好的
> 
> 更换至1.4.3-M2版本后,JSON解析正常

但是我昨天晚上发现的一个问题,在开发环境运行`.run`函数可以正常登录,但是在生产环境运行`.run`函数会**阻塞**,无法正常登录并接收频道消息

**Comment by TihPct** [comment]
> > > > 试试预发版本1.4.3-M2 是否解决问题
> > > 
> > > 
> > > 好的
> > 
> > 
> > 更换至1.4.3-M2版本后,JSON解析正常
> 
> 但是我昨天晚上发现了一个问题,在开发环境运行`.run`函数可以正常登录,但是在生产环境运行`.run`后,starter.getWssWorker()会报错`NullPointerException`
`Caused by: java.lang.NullPointerException: null
	at pers.pc2.huali.init.impl.ConfigInitImpl.loadChannelBot(ConfigInitImpl.java:87)
	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7.CGLIB$loadChannelBot$3(<generated>)
	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7$$FastClassBySpringCGLIB$$616af586.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7.loadChannelBot(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 27 common frames omitted
`
下面是我自己的用例
![image](https://user-images.githubusercontent.com/51705716/224464808-ccb701db-b2c1-4845-9929-de639b69b51e.png)

**Comment by TihPct** [comment]
> > > > > 试试预发版本1.4.3-M2 是否解决问题
> > > > 
> > > > 
> > > > 好的
> > > 
> > > 
> > > 更换至1.4.3-M2版本后,JSON解析正常
> > 
> > 
> > 但是我昨天晚上发现了一个问题,在开发环境运行`.run`函数可以正常登录,但是在生产环境运行`.run`后,starter.getWssWorker()会报错`NullPointerException`
> > `Caused by: java.lang.NullPointerException: null 	at pers.pc2.huali.init.impl.ConfigInitImpl.loadChannelBot(ConfigInitImpl.java:87) 	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7.CGLIB$loadChannelBot$3(<generated>) 	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7$$FastClassBySpringCGLIB$$616af586.invoke(<generated>) 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) 	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7.loadChannelBot(<generated>) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) 	... 27 common frames omitted `
> > 下面是我自己的用例
> > ![image](https://user-images.githubusercontent.com/51705716/224464808-ccb701db-b2c1-4845-9929-de639b69b51e.png)

补充控制台日志
![image](https://user-images.githubusercontent.com/51705716/224464867-d53eb9a0-d033-4287-a53a-a5f7e02fcd27.png)

**Comment by Kloping** [comment]
> > > > > > 试试预发版本1.4.3-M2 是否解决问题
> > > > > 
> > > > > 
> > > > > 好的
> > > > 
> > > > 
> > > > 更换至1.4.3-M2版本后,JSON解析正常
> > > 
> > > 
> > > 但是我昨天晚上发现了一个问题,在开发环境运行`.run`函数可以正常登录,但是在生产环境运行`.run`后,starter.getWssWorker()会报错`NullPointerException`
> > > `Caused by: java.lang.NullPointerException: null 	at pers.pc2.huali.init.impl.ConfigInitImpl.loadChannelBot(ConfigInitImpl.java:87) 	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7.CGLIB$loadChannelBot$3(<generated>) 	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7$$FastClassBySpringCGLIB$$616af586.invoke(<generated>) 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) 	at pers.pc2.huali.init.impl.ConfigInitImpl$$EnhancerBySpringCGLIB$$e8345be7.loadChannelBot(<generated>) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) 	... 27 common frames omitted `
> > > 下面是我自己的用例
> > > ![image](https://user-images.githubusercontent.com/51705716/224464808-ccb701db-b2c1-4845-9929-de639b69b51e.png)
> 
> 补充控制台日志 ![image](https://user-images.githubusercontent.com/51705716/224464867-d53eb9a0-d033-4287-a53a-a5f7e02fcd27.png)

使用的jdk版本是不是高了 目前在jdk11 jdk8 都是正常的

**Comment by TihPct** [comment]
> Owner

生产环境是jer8环境,开发环境是jdk1.8

**Comment by Kloping** [comment]
> > Owner
> 
> 生产环境是jre8环境,开发环境是jdk1.8

是springboot吗 如何复现

**Comment by TihPct** [comment]
> > > Owner
> > 
> > 
> > 生产环境是jre8环境,开发环境是jdk1.8
> 
> 是springboot吗 如何复现

是SpringBoot环境,版本是2.5.5,只需要引入Spring Boot 2.5.5版本依赖并打包即可
Maven Build
```
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
</build>
```

**Comment by Kloping** [comment]
> > > > Owner
> > > 
> > > 
> > > 生产环境是jre8环境,开发环境是jdk1.8
> > 
> > 
> > 是springboot吗 如何复现
> 
> 是SpringBoot环境,版本是2.5.5,只需要引入Spring Boot 2.5.5版本依赖并打包即可 Maven Build
> 
> ```
> <build>
>         <plugins>
>             <plugin>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-maven-plugin</artifactId>
>                 <configuration>
>                     <excludes>
>                         <exclude>
>                             <groupId>org.projectlombok</groupId>
>                             <artifactId>lombok</artifactId>
>                         </exclude>
>                     </excludes>
>                 </configuration>
>             </plugin>
>         </plugins>
> </build>
> ```

换个打包方式吧 这个一时半会很难解决
