### ISSUE TITLE
目前官方bot发主动消息是有什么限制吗 以及如果主动消息被拒绝可否添加一个报错

### ISSUE THREAD

**Issue by Shizoukia** [Kloping/qqpd-bot-java#33]
如题 我的bot似乎存在一个主动发消息给群的限制 调用发消息方法后日志也没报错也没任何回显 消息也没发出去:(

![image](https://github.com/user-attachments/assets/01c3a288-c7f7-4a1e-a4c8-4512e508d6ac)

**Comment by Shizoukia** [comment]
我没去研究那个官方wiki 我感觉似乎帮助不大 他那个wiki的内容太老了 我想找点什么报错码都没更新 如果开发者您知道什么原因可否告诉我一下 我进不去qq频道 他不同意我的申请;w; 麻烦了

**Comment by Kloping** [comment]
> 如题 我的bot似乎存在一个主动发消息给群的限制 调用发消息方法后日志也没报错也没任何回显 消息也没发出去:(
> 
> ![image](https://private-user-images.githubusercontent.com/103182720/366636735-01c3a288-c7f7-4a1e-a4c8-4512e508d6ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDI1NzIsIm5iZiI6MTcyNjEwMjI3MiwicGF0aCI6Ii8xMDMxODI3MjAvMzY2NjM2NzM1LTAxYzNhMjg4LWM3ZjctNGExZS1hNGM4LTQ1MTJlNTA4ZDZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwMDUxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGI1ZjU5ZGVmNzBkMmEyMDliOWUyNTAzNjFhMGJiMWE5MGI3ZDA4YWUxZjU5MTViNjVmN2IxOGI5YjNhYzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KNPR37zbOoKwB5pPVnzj-jVDE7llS7IImwGh8IirWks)

设置日志等级为0 会有显示 

    starter.APPLICATION.logger.setLogLevel(0);

**Comment by Shizoukia** [comment]
> > 如题 我的bot似乎存在一个主动发消息给群的限制 调用发消息方法后日志也没报错也没任何回显 消息也没发出去:(
> > ![image](https://private-user-images.githubusercontent.com/103182720/366636735-01c3a288-c7f7-4a1e-a4c8-4512e508d6ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDI1NzIsIm5iZiI6MTcyNjEwMjI3MiwicGF0aCI6Ii8xMDMxODI3MjAvMzY2NjM2NzM1LTAxYzNhMjg4LWM3ZjctNGExZS1hNGM4LTQ1MTJlNTA4ZDZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwMDUxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGI1ZjU5ZGVmNzBkMmEyMDliOWUyNTAzNjFhMGJiMWE5MGI3ZDA4YWUxZjU5MTViNjVmN2IxOGI5YjNhYzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KNPR37zbOoKwB5pPVnzj-jVDE7llS7IImwGh8IirWks)
> 
> 设置日志等级为0 会有显示
> 
> ```
> starter.APPLICATION.logger.setLogLevel(0);
> ```

![image](https://github.com/user-attachments/assets/b0322d8e-2daa-44f1-bfaf-bd5df31948c3)
我在main方法里加了这个 似乎没啥用处 huh

**Comment by Shizoukia** [comment]
以及有啥办法可以看出来bot是否运行在沙箱 我似乎不太清楚这个怎么区分 刚才审核给我拒绝了说我指令全未响应 我没给沙箱设置为true理论上是关闭状态吧huh

**Comment by Kloping** [comment]
> > > 如题 我的bot似乎存在一个主动发消息给群的限制 调用发消息方法后日志也没报错也没任何回显 消息也没发出去:(
> > > ![image](https://private-user-images.githubusercontent.com/103182720/366636735-01c3a288-c7f7-4a1e-a4c8-4512e508d6ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDI1NzIsIm5iZiI6MTcyNjEwMjI3MiwicGF0aCI6Ii8xMDMxODI3MjAvMzY2NjM2NzM1LTAxYzNhMjg4LWM3ZjctNGExZS1hNGM4LTQ1MTJlNTA4ZDZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwMDUxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGI1ZjU5ZGVmNzBkMmEyMDliOWUyNTAzNjFhMGJiMWE5MGI3ZDA4YWUxZjU5MTViNjVmN2IxOGI5YjNhYzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KNPR37zbOoKwB5pPVnzj-jVDE7llS7IImwGh8IirWks)
> > 
> > 
> > 设置日志等级为0 会有显示
> > ```
> > starter.APPLICATION.logger.setLogLevel(0);
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/103182720/366743939-b0322d8e-2daa-44f1-bfaf-bd5df31948c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjQyODcsIm5iZiI6MTcyNjEyMzk4NywicGF0aCI6Ii8xMDMxODI3MjAvMzY2NzQzOTM5LWIwMzIyZDhlLTJkYWEtNDRmMS1iZmFmLWJkNWRmMzE5NDhjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwNjUzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTQzYjZlOWQ1ODYzOTVlYWFlNDY2OGQ2NmZhMzYwMGUxMjIzOTZiY2JiMDBlODk1OWM0YTJlMzkwNWE0Y2ZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cXhCitbt5VixCFMSbvjyg3yJBT6XOKWslG9_IESph1c) 我在main方法里加了这个 似乎没啥用处 huh

放在run之后

**Comment by Kloping** [comment]
> 以及有啥办法可以看出来bot是否运行在沙箱 我似乎不太清楚这个怎么区分 刚才审核给我拒绝了说我指令全未响应 我没给沙箱设置为true理论上是关闭状态吧huh

q.qq.com 控制台看

**Comment by Shizoukia** [comment]
好的 日志正常打印了 我似乎看到一些不正常的消息
他提示说什么消息在审核 最近qq机器人有啥情况变动吗
大佬可否加个qq详细聊一下qwq

```[qq-pd-group][Info]  [09/12-16:22:08:576]=>Bot(SweetNeko-测试中) post([type(USER) 6A07A47A82FFC56A859CBC83068A454A].6A07A47A82FFC56A859CBC83068A454A:/sendmsg 42649DB356FEE94FB343C227041AE778 e) from FriendMessageEvent
[qq-pd-group][Normal][09/12-16:22:08:813]=>Use the (POST) method through the (GroupBaseV2) interface to request the data obtained by the response code of the (https://api.sgroup.qq.com/v2/groups/42649DB356FEE94FB343C227041AE778/messages) URL is (200), and ({"id":"msg_tid_-打个码","timestamp":"2024-09-12T16:22:08+08:00","audit_id":"msg_tid_-打个码","audit_tips":"group push message is waiting for audit now"}) may be converted to (V2Result(id=打个码, timestamp=1726129328000, group_code=null, ret=200, msg=null, file_uuid=null, file_info=null, ttl=null)) type Will be processed and filtered
[qq-pd-group][Normal][09/12-16:22:09:059]=>Use the (POST) method through the (UserBaseV2) interface to request the data obtained by the response code of the (https://api.sgroup.qq.com/v2/users/6A07A47A82FFC56A859CBC83068A454A/messages) URL is (200), and ({"id":"打个码!!","timestamp":"2024-09-12T16:22:09+08:00"}) may be converted to (V2Result(id=打个码!!, timestamp=1726129329000, group_code=null, ret=200, msg=null, file_uuid=null, file_info=null, ttl=null)) type Will be processed and filtered
[qq-pd-group][Normal][09/12-16:22:32:667]=>wss send: {"d":2,"op":1}
[qq-pd-group][Normal][09/12-16:22:32:719]=>receive {"op":11}```

**Comment by Shizoukia** [comment]
> 好的 日志正常打印了 我似乎看到一些不正常的消息 他提示说什么消息在审核 最近qq机器人有啥情况变动吗 大佬可否加个qq详细聊一下qwq
> 
> ```
> [qq-pd-group][Normal][09/12-16:22:08:813]=>Use the (POST) method through the (GroupBaseV2) interface to request the data obtained by the response code of the (https://api.sgroup.qq.com/v2/groups/42649DB356FEE94FB343C227041AE778/messages) URL is (200), and ({"id":"msg_tid_-打个码","timestamp":"2024-09-12T16:22:08+08:00","audit_id":"msg_tid_-打个码","audit_tips":"group push message is waiting for audit now"}) may be converted to (V2Result(id=打个码, timestamp=1726129328000, group_code=null, ret=200, msg=null, file_uuid=null, file_info=null, ttl=null)) type Will be processed and filtered
> [qq-pd-group][Normal][09/12-16:22:09:059]=>Use the (POST) method through the (UserBaseV2) interface to request the data obtained by the response code of the (https://api.sgroup.qq.com/v2/users/6A07A47A82FFC56A859CBC83068A454A/messages) URL is (200), and ({"id":"打个码!!","timestamp":"2024-09-12T16:22:09+08:00"}) may be converted to (V2Result(id=打个码!!, timestamp=1726129329000, group_code=null, ret=200, msg=null, file_uuid=null, file_info=null, ttl=null)) type Will be processed and filtered
> [qq-pd-group][Normal][09/12-16:22:32:667]=>wss send: {"d":2,"op":1}
> [qq-pd-group][Normal][09/12-16:22:32:719]=>receive {"op":11}```
> ```

我的机器人现在正在申请上线审核中 和这个有影响吗

**Comment by Kloping** [comment]
> 好的 日志正常打印了 我似乎看到一些不正常的消息 他提示说什么消息在审核 最近qq机器人有啥情况变动吗 大佬可否加个qq详细聊一下qwq
> 
> ```
> [qq-pd-group][Normal][09/12-16:22:08:813]=>Use the (POST) method through the (GroupBaseV2) interface to request the data obtained by the response code of the (https://api.sgroup.qq.com/v2/groups/42649DB356FEE94FB343C227041AE778/messages) URL is (200), and ({"id":"msg_tid_-打个码","timestamp":"2024-09-12T16:22:08+08:00","audit_id":"msg_tid_-打个码","audit_tips":"group push message is waiting for audit now"}) may be converted to (V2Result(id=打个码, timestamp=1726129328000, group_code=null, ret=200, msg=null, file_uuid=null, file_info=null, ttl=null)) type Will be processed and filtered
> [qq-pd-group][Normal][09/12-16:22:09:059]=>Use the (POST) method through the (UserBaseV2) interface to request the data obtained by the response code of the (https://api.sgroup.qq.com/v2/users/6A07A47A82FFC56A859CBC83068A454A/messages) URL is (200), and ({"id":"打个码!!","timestamp":"2024-09-12T16:22:09+08:00"}) may be converted to (V2Result(id=打个码!!, timestamp=1726129329000, group_code=null, ret=200, msg=null, file_uuid=null, file_info=null, ttl=null)) type Will be processed and filtered
> [qq-pd-group][Normal][09/12-16:22:32:667]=>wss send: {"d":2,"op":1}
> [qq-pd-group][Normal][09/12-16:22:32:719]=>receive {"op":11}```
> ```

主页有q群
