### ISSUE TITLE
有无一个Join/Quit Group/Channel event

### ISSUE THREAD

**Issue by xiaojiang233** [Kloping/qqpd-bot-java#34]
为了做多群适配

**Comment by Kloping** [comment]
- GroupDelRobotEvent
- GroupAddRobotEvent
- GUILD_DELETE
- GUILD_CREATE

**Comment by Kloping** [comment]
GuildUpdateEvent

**Comment by Kloping** [comment]
关于更多请[加入群聊](点击链接加入群聊【插件/交流群】：https://qm.qq.com/q/vm4dz5aZWw) 交流
