### ISSUE TITLE
大佬我想问问resumeConnect的问题

### ISSUE THREAD

**Issue by 2195517546** [Kloping/qqpd-bot-java#35]
我发现大佬的代码在io.github.kloping.qqbot.network包下的AuthAndHeartbeat.java下的resumeConnect方法似乎并没有用到，或者是我没发现他用到了，因为我每次发resume的payload
比如{"d":{"token":"QQBot XXXX","session_id":"0","seq":1},"op":6}的时候他都会给我返回{"op":9,"d":false}不知道怎么解决我就每次断联的时候直接重新连了
所以为了解决这个问题才来看看别人的代码怎么写的想向你请教谢谢。。。

**Comment by Kloping** [comment]
确实没有用到 因为很少会用到
你是在 4009 的时候发的吗
- [针对 websocket 错误码的简单处理逻辑](https://bot.q.qq.com/wiki/develop/api-v2/dev-prepare/error-trace/websocket.html#%E9%92%88%E5%AF%B9-websocket-%E9%94%99%E8%AF%AF%E7%A0%81%E7%9A%84%E7%AE%80%E5%8D%95%E5%A4%84%E7%90%86%E9%80%BB%E8%BE%91)
